services:
  identity:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: .
      dockerfile: Identity/Dockerfile
    environment:
      - ESGI_API_KEY=${ESGI_API_KEY}
      - ENV_SUFFIX=IDENTITY
      - DB_SERVER=${DB_SERVER_IDENTITY}
      - DB_PORT=${DB_PORT_IDENTITY}
      - DB_NAME=${DB_NAME_IDENTITY}
      - DB_USER=${DB_USER_IDENTITY}
      - DB_PASS=${DB_PASS_IDENTITY}
    ports:
      - "5046:8080"

  rassoapi:
    image: ${DOCKER_REGISTRY-}rassoapi
    build:
      context: .
      dockerfile: RassoApi/Dockerfile
    environment:
      - ESGI_API_KEY=${ESGI_API_KEY}
      - ENV_SUFFIX=RASSOAPI
      - DB_SERVER=${DB_SERVER_RASSOAPI}
      - DB_PORT=${DB_PORT_RASSOAPI}
      - DB_NAME=${DB_NAME_RASSOAPI}
      - DB_USER=${DB_USER_RASSOAPI}
      - DB_PASS=${DB_PASS_RASSOAPI}

    ports:
      - "5048:8080"