name: Publish RassoApi Client

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/RassoApi.Client/client-ts/**'

  pull_request:
    branches:
      - 'users/**'
    paths:
      - 'Backend/RassoApi.Client/client-ts/**'

jobs:
  publish-client:
    uses: ./.github/workflows/publish-client.yml
    with:
      client-path: Backend/RassoApi.Client/client-ts
    secrets: inherit
