name: Publish TypeScript Client

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend/RassoApi.Client

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 9 (préversion)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.100-preview.4'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - name: Install NSwag CLI
        run: dotnet tool install --global NSwag.ConsoleCore

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Génère le client TypeScript
        run: nswag run ts-nswag.json  # ou le nom réel

      - name: Vérifie le client généré
        run: ls -R Generated/rasso-api-client

      - name: Install dependencies
        run: npm install
        working-directory: Backend/RassoApi.Client/Generated/rasso-api-client

      - name: Build client
        run: npm run build
        working-directory: Backend/RassoApi.Client/Generated/rasso-api-client

      - name: Publish to GitHub Packages
        run: npm publish
        working-directory: Backend/RassoApi.Client/Generated/rasso-api-client
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
