name: Publish TypeScript Client

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Vérifie le contenu après checkout
        run: ls -R

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - name: Install NSwag CLI
        run: dotnet tool install --global NSwag.ConsoleCore

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run NSwag
        run: nswag run path/to/your-config.nswag


      - name: Génère le client TypeScript
        run: nswag run path/to/your-config.nswag

      - name: Vérifie le dossier généré
        run: ls -R Backend/RassoApi.Client/Generated/

      - name: Install dependencies
        run: npm install
        working-directory: Backend/RassoApi.Client/Generated/rasso-api-client

      - name: Build client
        run: npm run build
        working-directory: Backend/RassoApi.Client/Generated/rasso-api-client

      - name: Publish to GitHub Packages
        run: npm publish
        working-directory: Backend/RassoApi.Client/Generated/rasso-api-client
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
