name: Publish Identity Client

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/Identity.Client/client-ts/**'

  pull_request:
    branches:
      - 'users/**'
    paths:
      - 'Backend/Identity.Client/client-ts/**'

jobs:
  publish-client:
    uses: ./.github/workflows/reusable-publish-client.yml
    with:
      client-path: Backend/Identity.Client/client-ts
    secrets: inherit
