name: Publish Identity Client

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/Identity.Client/client-ts/**'

  pull_request:
    branches:
      - 'users/**'
    paths:
      - 'Backend/Identity.Client/client-ts/**'
      
  workflow_dispatch:

  
jobs:
  publish-client:
    uses: ./.github/workflows/publish-client.yml
    with:
      client-path: Backend/Identity.Client/client-ts
      package-name: '@mmaesgi/identity-client'
      
  
    secrets: inherit

