name: Publish TypeScript Client

on:
  push:
    branches: [main]
    
permissions:
  contents: read
  packages: write
  
jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend/RassoApi.Client/client-ts

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 9 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.X'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - name: Install NSwag CLI
        run: dotnet tool install --global NSwag.ConsoleCore

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Génère le client TypeScript
        run: nswag run ts-nswag.json 

      - name: Vérifie le client généré
        run: ls -R .

      - name: Install dependencies
        run: npm install

      - name: Build client
        run: npm run build

      - name: Publish to GitHub Packages
        run: npm publish

        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
